package com.grotto.grotto.model.home.pojo;
// Generated Apr 29, 2015 1:19:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmergencyList generated by hbm2java
 */
@Entity
@Table(name="emergency_list"
    ,catalog="mydb"
)
public class EmergencyList extends AbstractPojo<EmergencyList, Integer> implements java.io.Serializable{


     private Integer id;
     private Users users;
     private String phoneNumber;
     private Integer type;
     private String uuid;
     private Set<UsersHasEmergencyList> usersHasEmergencyLists = new HashSet<UsersHasEmergencyList>(0);

    public EmergencyList() {
    }

    public EmergencyList(Users users, String phoneNumber, Integer type, String uuid, Set<UsersHasEmergencyList> usersHasEmergencyLists) {
       this.users = users;
       this.phoneNumber = phoneNumber;
       this.type = type;
       this.uuid = uuid;
       this.usersHasEmergencyLists = usersHasEmergencyLists;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="users_id")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="phone_number", length=45)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="type")
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }

    
    @Column(name="uuid", length=100)
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="emergencyList")
    public Set<UsersHasEmergencyList> getUsersHasEmergencyLists() {
        return this.usersHasEmergencyLists;
    }
    
    public void setUsersHasEmergencyLists(Set<UsersHasEmergencyList> usersHasEmergencyLists) {
        this.usersHasEmergencyLists = usersHasEmergencyLists;
    }

    @Override
    public Integer findID() {
        return getId();
    }




}


