package com.grotto.grotto.model.home.pojo;
// Generated Apr 29, 2015 1:19:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HardwareComponents generated by hbm2java
 */
@Entity
@Table(name="hardware_components"
    ,catalog="mydb"
)
public class HardwareComponents  extends AbstractPojo<HardwareComponents, Integer>implements java.io.Serializable {


     private Integer id;
     private Hubs hubs;
     private Integer type;
     private String uuid;
     private Set<ShelfCells> shelfCellses = new HashSet<ShelfCells>(0);

    public HardwareComponents() {
    }

	
    public HardwareComponents(Hubs hubs) {
        this.hubs = hubs;
    }
    public HardwareComponents(Hubs hubs, Integer type, String uuid, Set<ShelfCells> shelfCellses) {
       this.hubs = hubs;
       this.type = type;
       this.uuid = uuid;
       this.shelfCellses = shelfCellses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hubs_id", nullable=false)
    public Hubs getHubs() {
        return this.hubs;
    }
    
    public void setHubs(Hubs hubs) {
        this.hubs = hubs;
    }

    
    @Column(name="type")
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }

    
    @Column(name="uuid", length=100)
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hardwareComponents")
    public Set<ShelfCells> getShelfCellses() {
        return this.shelfCellses;
    }
    
    public void setShelfCellses(Set<ShelfCells> shelfCellses) {
        this.shelfCellses = shelfCellses;
    }

    @Override
    public Integer findID() {
        return getId();
    }




}


