package com.grotto.grotto.model.home.pojo;
// Generated Apr 29, 2015 1:19:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hubs generated by hbm2java
 */
@Entity
@Table(name="hubs"
    ,catalog="mydb"
)
public class Hubs extends AbstractPojo<Hubs, Integer> implements java.io.Serializable{


     private Integer id;
     private String ip;
     private String name;
     private String manfactuarId;
     private String uuid;
      private Set<HubsHasSupermarkets> hubsHasSupermarketses = new HashSet<HubsHasSupermarkets>(0);
     private Set<UsersHaveHubs> usersHaveHubses = new HashSet<UsersHaveHubs>(0);
     private Set<HardwareComponents> hardwareComponentses = new HashSet<HardwareComponents>(0);

    public Hubs() {
    }

    public Hubs(String ip, String name, String manfactuarId, String uuid, Set hubsHasSupermarketses, Set usersHaveHubses, Set hardwareComponentses) {
       this.ip = ip;
       this.name = name;
       this.manfactuarId = manfactuarId;
       this.uuid = uuid;
       this.hubsHasSupermarketses = hubsHasSupermarketses;
       this.usersHaveHubses = usersHaveHubses;
       this.hardwareComponentses = hardwareComponentses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ip", length=45)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="manfactuar_id", length=45)
    public String getManfactuarId() {
        return this.manfactuarId;
    }
    
    public void setManfactuarId(String manfactuarId) {
        this.manfactuarId = manfactuarId;
    }

    
    @Column(name="uuid", length=100)
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hubs")
    public Set<HubsHasSupermarkets> getHubsHasSupermarketses() {
        return this.hubsHasSupermarketses;
    }
    
    public void setHubsHasSupermarketses(Set<HubsHasSupermarkets> hubsHasSupermarketses) {
        this.hubsHasSupermarketses = hubsHasSupermarketses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hubs")
    public Set<UsersHaveHubs> getUsersHaveHubses() {
        return this.usersHaveHubses;
    }
    
    public void setUsersHaveHubses(Set<UsersHaveHubs>usersHaveHubses) {
        this.usersHaveHubses = usersHaveHubses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hubs")
    public Set<HardwareComponents> getHardwareComponentses() {
        return this.hardwareComponentses;
    }
    
    public void setHardwareComponentses(Set<HardwareComponents> hardwareComponentses) {
        this.hardwareComponentses = hardwareComponentses;
    }

    @Override
    public Integer findID() {
       return getId();
    }




}


