package com.grotto.grotto.model.home.pojo;
// Generated Apr 29, 2015 1:19:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HubsHasSupermarketsId generated by hbm2java
 */
@Embeddable
public class HubsHasSupermarketsId  implements java.io.Serializable {


     private int hubsId;
     private int supermarketsId;

    public HubsHasSupermarketsId() {
    }

    public HubsHasSupermarketsId(int hubsId, int supermarketsId) {
       this.hubsId = hubsId;
       this.supermarketsId = supermarketsId;
    }
   


    @Column(name="hubs_id", nullable=false)
    public int getHubsId() {
        return this.hubsId;
    }
    
    public void setHubsId(int hubsId) {
        this.hubsId = hubsId;
    }


    @Column(name="supermarkets_id", nullable=false)
    public int getSupermarketsId() {
        return this.supermarketsId;
    }
    
    public void setSupermarketsId(int supermarketsId) {
        this.supermarketsId = supermarketsId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HubsHasSupermarketsId) ) return false;
		 HubsHasSupermarketsId castOther = ( HubsHasSupermarketsId ) other; 
         
		 return (this.getHubsId()==castOther.getHubsId())
 && (this.getSupermarketsId()==castOther.getSupermarketsId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getHubsId();
         result = 37 * result + this.getSupermarketsId();
         return result;
   }   


}


