package com.grotto.grotto.model.home.pojo;
// Generated Apr 29, 2015 1:19:13 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HubsHasSupermarkets generated by hbm2java
 */
@Entity
@Table(name="hubs_has_supermarkets"
    ,catalog="mydb"
)
public class HubsHasSupermarkets  implements java.io.Serializable {


     private HubsHasSupermarketsId id;
     private Hubs hubs;
     private Supermarkets supermarkets;

    public HubsHasSupermarkets() {
    }

    public HubsHasSupermarkets(HubsHasSupermarketsId id, Hubs hubs, Supermarkets supermarkets) {
       this.id = id;
       this.hubs = hubs;
       this.supermarkets = supermarkets;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="hubsId", column=@Column(name="hubs_id", nullable=false) ), 
        @AttributeOverride(name="supermarketsId", column=@Column(name="supermarkets_id", nullable=false) ) } )
    public HubsHasSupermarketsId getId() {
        return this.id;
    }
    
    public void setId(HubsHasSupermarketsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hubs_id", nullable=false, insertable=false, updatable=false)
    public Hubs getHubs() {
        return this.hubs;
    }
    
    public void setHubs(Hubs hubs) {
        this.hubs = hubs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="supermarkets_id", nullable=false, insertable=false, updatable=false)
    public Supermarkets getSupermarkets() {
        return this.supermarkets;
    }
    
    public void setSupermarkets(Supermarkets supermarkets) {
        this.supermarkets = supermarkets;
    }




}


