package com.grotto.grotto.model.home.pojo;
// Generated Apr 29, 2015 1:19:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductBrands generated by hbm2java
 */
@Entity
@Table(name="product_brands"
    ,catalog="mydb"
)
public class ProductBrands  extends AbstractPojo<ProductBrands, Integer> implements java.io.Serializable  {


     private Integer id;
     private Products products;
     private String productBrandName;
     private String uuid;
    private Set<ShelfCells> shelfCellses = new HashSet<ShelfCells>(0);

    public ProductBrands() {
    }

	
    public ProductBrands(Products products) {
        this.products = products;
    }
    public ProductBrands(Products products, String productBrandName, String uuid, Set shelfCellses) {
       this.products = products;
       this.productBrandName = productBrandName;
       this.uuid = uuid;
       this.shelfCellses = shelfCellses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="products_id", nullable=false)
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

    
    @Column(name="product_brand_name", length=45)
    public String getProductBrandName() {
        return this.productBrandName;
    }
    
    public void setProductBrandName(String productBrandName) {
        this.productBrandName = productBrandName;
    }

    
    @Column(name="uuid", length=100)
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productBrands")
    public Set<ShelfCells> getShelfCellses() {
        return this.shelfCellses;
    }
    
    public void setShelfCellses(Set<ShelfCells> shelfCellses) {
        this.shelfCellses = shelfCellses;
    }

    @Override
    public Integer findID() {
return getId();
    }




}


