package com.grotto.grotto.model.home.pojo;
// Generated Apr 29, 2015 1:19:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ShelfCells generated by hbm2java
 */
@Entity
@Table(name="shelf_cells"
    ,catalog="mydb"
)
public class ShelfCells  implements java.io.Serializable {


     private Integer id;
     private HardwareComponents hardwareComponents;
     private ProductBrands productBrands;
     private Float minWeight;
     private Float requestQuantity;
     private Integer position;
     private Integer automaticConf;
     private String uuid;

    public ShelfCells() {
    }

	
    public ShelfCells(HardwareComponents hardwareComponents, ProductBrands productBrands) {
        this.hardwareComponents = hardwareComponents;
        this.productBrands = productBrands;
    }
    public ShelfCells(HardwareComponents hardwareComponents, ProductBrands productBrands, Float minWeight, Float requestQuantity, Integer position, Integer automaticConf, String uuid) {
       this.hardwareComponents = hardwareComponents;
       this.productBrands = productBrands;
       this.minWeight = minWeight;
       this.requestQuantity = requestQuantity;
       this.position = position;
       this.automaticConf = automaticConf;
       this.uuid = uuid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hardware_components_id", nullable=false)
    public HardwareComponents getHardwareComponents() {
        return this.hardwareComponents;
    }
    
    public void setHardwareComponents(HardwareComponents hardwareComponents) {
        this.hardwareComponents = hardwareComponents;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_brands_id", nullable=false)
    public ProductBrands getProductBrands() {
        return this.productBrands;
    }
    
    public void setProductBrands(ProductBrands productBrands) {
        this.productBrands = productBrands;
    }

    
    @Column(name="min_weight", precision=12, scale=0)
    public Float getMinWeight() {
        return this.minWeight;
    }
    
    public void setMinWeight(Float minWeight) {
        this.minWeight = minWeight;
    }

    
    @Column(name="request_quantity", precision=12, scale=0)
    public Float getRequestQuantity() {
        return this.requestQuantity;
    }
    
    public void setRequestQuantity(Float requestQuantity) {
        this.requestQuantity = requestQuantity;
    }

    
    @Column(name="position")
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }

    
    @Column(name="automatic_conf")
    public Integer getAutomaticConf() {
        return this.automaticConf;
    }
    
    public void setAutomaticConf(Integer automaticConf) {
        this.automaticConf = automaticConf;
    }

    
    @Column(name="uuid", length=100)
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


