package com.grotto.grotto.model.home.pojo;
// Generated Apr 29, 2015 1:19:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Supermarkets generated by hbm2java
 */
@Entity
@Table(name="supermarkets"
    ,catalog="mydb"
)
public class Supermarkets extends AbstractPojo<Supermarkets, Integer> implements java.io.Serializable {


     private Integer id;
     private String name;
     private String phoneNumber;
     private String adress;
     private String longitude;
     private String latitude;
     private String uuid;
    private Set<HubsHasSupermarkets> hubsHasSupermarketses = new HashSet<HubsHasSupermarkets>(0);

    public Supermarkets() {
    }

    public Supermarkets(String name, String phoneNumber, String adress, String longitude, String latitude, String uuid, Set hubsHasSupermarketses) {
       this.name = name;
       this.phoneNumber = phoneNumber;
       this.adress = adress;
       this.longitude = longitude;
       this.latitude = latitude;
       this.uuid = uuid;
       this.hubsHasSupermarketses = hubsHasSupermarketses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="phone_number", length=45)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="adress", length=45)
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }

    
    @Column(name="longitude", length=45)
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="latitude", length=45)
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="uuid", length=100)
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="supermarkets")
    public Set<HubsHasSupermarkets> getHubsHasSupermarketses() {
        return this.hubsHasSupermarketses;
    }
    
    public void setHubsHasSupermarketses(Set<HubsHasSupermarkets> hubsHasSupermarketses) {
        this.hubsHasSupermarketses = hubsHasSupermarketses;
    }

    @Override
    public Integer findID() {
       return getId();
    }




}


