package com.grotto.grotto.model.home.pojo;
// Generated Apr 29, 2015 1:19:13 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersHasEmergencyList generated by hbm2java
 */
@Entity
@Table(name="users_has_emergency_list"
    ,catalog="mydb"
)
public class UsersHasEmergencyList  implements java.io.Serializable {


     private UsersHasEmergencyListId id;
     private EmergencyList emergencyList;
     private Users users;

    public UsersHasEmergencyList() {
    }

    public UsersHasEmergencyList(UsersHasEmergencyListId id, EmergencyList emergencyList, Users users) {
       this.id = id;
       this.emergencyList = emergencyList;
       this.users = users;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="usersId", column=@Column(name="users_id", nullable=false) ), 
        @AttributeOverride(name="emergencyListId", column=@Column(name="emergency_list_id", nullable=false) ) } )
    public UsersHasEmergencyListId getId() {
        return this.id;
    }
    
    public void setId(UsersHasEmergencyListId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emergency_list_id", nullable=false, insertable=false, updatable=false)
    public EmergencyList getEmergencyList() {
        return this.emergencyList;
    }
    
    public void setEmergencyList(EmergencyList emergencyList) {
        this.emergencyList = emergencyList;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="users_id", nullable=false, insertable=false, updatable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


