package com.grotto.grotto.model.home.pojo;
// Generated Apr 29, 2015 1:19:13 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersHasNeibours generated by hbm2java
 */
@Entity
@Table(name="users_has_neibours"
    ,catalog="mydb"
)
public class UsersHasNeibours  implements java.io.Serializable {


     private UsersHasNeiboursId id;
     private Users usersByUsersId1;
     private Users usersByUsersId;

    public UsersHasNeibours() {
    }

    public UsersHasNeibours(UsersHasNeiboursId id, Users usersByUsersId1, Users usersByUsersId) {
       this.id = id;
       this.usersByUsersId1 = usersByUsersId1;
       this.usersByUsersId = usersByUsersId;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="usersId", column=@Column(name="users_id", nullable=false) ), 
        @AttributeOverride(name="usersId1", column=@Column(name="users_id1", nullable=false) ) } )
    public UsersHasNeiboursId getId() {
        return this.id;
    }
    
    public void setId(UsersHasNeiboursId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="users_id1", nullable=false, insertable=false, updatable=false)
    public Users getUsersByUsersId1() {
        return this.usersByUsersId1;
    }
    
    public void setUsersByUsersId1(Users usersByUsersId1) {
        this.usersByUsersId1 = usersByUsersId1;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="users_id", nullable=false, insertable=false, updatable=false)
    public Users getUsersByUsersId() {
        return this.usersByUsersId;
    }
    
    public void setUsersByUsersId(Users usersByUsersId) {
        this.usersByUsersId = usersByUsersId;
    }




}


