package com.grotto.grotto.model.home.pojo;
// Generated Apr 29, 2015 1:19:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersSentRequestId generated by hbm2java
 */
@Embeddable
public class UsersSentRequestId  implements java.io.Serializable {


     private int usersId;
     private int usersId1;

    public UsersSentRequestId() {
    }

    public UsersSentRequestId(int usersId, int usersId1) {
       this.usersId = usersId;
       this.usersId1 = usersId1;
    }
   


    @Column(name="users_id", nullable=false)
    public int getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(int usersId) {
        this.usersId = usersId;
    }


    @Column(name="users_id1", nullable=false)
    public int getUsersId1() {
        return this.usersId1;
    }
    
    public void setUsersId1(int usersId1) {
        this.usersId1 = usersId1;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersSentRequestId) ) return false;
		 UsersSentRequestId castOther = ( UsersSentRequestId ) other; 
         
		 return (this.getUsersId()==castOther.getUsersId())
 && (this.getUsersId1()==castOther.getUsersId1());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsersId();
         result = 37 * result + this.getUsersId1();
         return result;
   }   


}


