package com.grotto.grotto.model.home.pojo;
// Generated Apr 29, 2015 1:19:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersHaveHubsId generated by hbm2java
 */
@Embeddable
public class UsersHaveHubsId  implements java.io.Serializable {


     private int hubsId;
     private int usersId;

    public UsersHaveHubsId() {
    }

    public UsersHaveHubsId(int hubsId, int usersId) {
       this.hubsId = hubsId;
       this.usersId = usersId;
    }
   


    @Column(name="hubs_id", nullable=false)
    public int getHubsId() {
        return this.hubsId;
    }
    
    public void setHubsId(int hubsId) {
        this.hubsId = hubsId;
    }


    @Column(name="users_id", nullable=false)
    public int getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(int usersId) {
        this.usersId = usersId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersHaveHubsId) ) return false;
		 UsersHaveHubsId castOther = ( UsersHaveHubsId ) other; 
         
		 return (this.getHubsId()==castOther.getHubsId())
 && (this.getUsersId()==castOther.getUsersId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getHubsId();
         result = 37 * result + this.getUsersId();
         return result;
   }   


}


