package com.grotto.grotto.model.home.pojo;
// Generated Apr 29, 2015 1:19:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersHasEmergencyListId generated by hbm2java
 */
@Embeddable
public class UsersHasEmergencyListId  implements java.io.Serializable {


     private int usersId;
     private int emergencyListId;

    public UsersHasEmergencyListId() {
    }

    public UsersHasEmergencyListId(int usersId, int emergencyListId) {
       this.usersId = usersId;
       this.emergencyListId = emergencyListId;
    }
   


    @Column(name="users_id", nullable=false)
    public int getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(int usersId) {
        this.usersId = usersId;
    }


    @Column(name="emergency_list_id", nullable=false)
    public int getEmergencyListId() {
        return this.emergencyListId;
    }
    
    public void setEmergencyListId(int emergencyListId) {
        this.emergencyListId = emergencyListId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersHasEmergencyListId) ) return false;
		 UsersHasEmergencyListId castOther = ( UsersHasEmergencyListId ) other; 
         
		 return (this.getUsersId()==castOther.getUsersId())
 && (this.getEmergencyListId()==castOther.getEmergencyListId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsersId();
         result = 37 * result + this.getEmergencyListId();
         return result;
   }   


}


