package com.grotto.grotto.model.home.pojo;
// Generated Apr 29, 2015 1:19:13 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersHaveHubs generated by hbm2java
 */
@Entity
@Table(name="users_have_hubs"
    ,catalog="mydb"
)
public class UsersHaveHubs  implements java.io.Serializable {


     private UsersHaveHubsId id;
     private Hubs hubs;
     private Users users;

    public UsersHaveHubs() {
    }

    public UsersHaveHubs(UsersHaveHubsId id, Hubs hubs, Users users) {
       this.id = id;
       this.hubs = hubs;
       this.users = users;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="hubsId", column=@Column(name="hubs_id", nullable=false) ), 
        @AttributeOverride(name="usersId", column=@Column(name="users_id", nullable=false) ) } )
    public UsersHaveHubsId getId() {
        return this.id;
    }
    
    public void setId(UsersHaveHubsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hubs_id", nullable=false, insertable=false, updatable=false)
    public Hubs getHubs() {
        return this.hubs;
    }
    
    public void setHubs(Hubs hubs) {
        this.hubs = hubs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="users_id", nullable=false, insertable=false, updatable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


